=== radtek/plsql_os_command/apidoc/application.dtd
<!ELEMENT APPLICATION ( OVERVIEW?, (PACKAGE | TABLE)*, GENERATOR? ) >
<!ATTLIST APPLICATION NAME CDATA #REQUIRED >

<!ELEMENT ARGUMENT ( COMMENT? ) >
<!ATTLIST ARGUMENT DEFAULT CDATA #IMPLIED >
<!ATTLIST ARGUMENT MODE CDATA #IMPLIED >
<!ATTLIST ARGUMENT NAME CDATA #REQUIRED >
<!ATTLIST ARGUMENT TYPE CDATA #REQUIRED >

<!ELEMENT COMMENT ( #PCDATA ) >

<!ELEMENT COMMENT_FIRST_LINE ( #PCDATA ) >

<!ELEMENT CONSTANT ( COMMENT | COMMENT_FIRST_LINE | RETURN )* >
<!ATTLIST CONSTANT NAME ID #REQUIRED >

<!ELEMENT CURSOR ( ARGUMENT | COMMENT | COMMENT_FIRST_LINE | RETURN )* >
<!ATTLIST CURSOR NAME CDATA #REQUIRED >

<!ELEMENT TAG ( COMMENT? ) >
<!ATTLIST TAG TYPE CDATA #REQUIRED >
<!ATTLIST TAG NAME CDATA #IMPLIED >

<!ELEMENT EXCEPTION ( #PCDATA ) >
<!ATTLIST EXCEPTION NAME CDATA #REQUIRED >

<!ELEMENT FUNCTION ( ARGUMENT | COMMENT | COMMENT_FIRST_LINE | RETURN | TAG )* >
<!ATTLIST FUNCTION NAME CDATA #REQUIRED >

<!ELEMENT OVERVIEW ( #PCDATA ) >

<!ELEMENT PACKAGE ( COMMENT | CONSTANT | CURSOR | EXCEPTION | FUNCTION | PROCEDURE | TYPE | VARIABLE | TAG )* >
<!ATTLIST PACKAGE NAME ID #REQUIRED >
<!ATTLIST PACKAGE SCHEMA CDATA #IMPLIED >

<!ELEMENT PROCEDURE ( ARGUMENT | COMMENT | COMMENT_FIRST_LINE | TAG )* >
<!ATTLIST PROCEDURE NAME CDATA #REQUIRED >

<!ELEMENT RETURN ( COMMENT? ) >
<!ATTLIST RETURN TYPE CDATA #REQUIRED >

<!ELEMENT THROWS ( COMMENT? ) >
<!ATTLIST THROWS NAME CDATA #REQUIRED >

<!ELEMENT FIELD ( COMMENT? ) >
<!ATTLIST FIELD NAME CDATA #REQUIRED >
<!ATTLIST FIELD TYPE CDATA #REQUIRED >

<!ELEMENT TYPE ( COMMENT | COMMENT_FIRST_LINE | FIELD | RETURN | TAG )* >
<!ATTLIST TYPE NAME CDATA #REQUIRED >

<!ELEMENT VARIABLE ( COMMENT | COMMENT_FIRST_LINE | RETURN )* >
<!ATTLIST VARIABLE NAME ID #REQUIRED >

<!ELEMENT TABLE ( COMMENT | COLUMN | TAG )* >
<!ATTLIST TABLE NAME ID #REQUIRED >
<!ATTLIST TABLE SCHEMA CDATA #IMPLIED >

<!ELEMENT COLUMN ( COMMENT? ) >
<!ATTLIST COLUMN CONSTRAINT CDATA #IMPLIED >
<!ATTLIST COLUMN NAME CDATA #REQUIRED >
<!ATTLIST COLUMN TYPE CDATA #REQUIRED >

<!ELEMENT GENERATOR ( OBJECTS, CREATED ) >

<!ELEMENT OBJECTS ( PROCESSED, SKIPPED ) >

<!ELEMENT PROCESSED EMPTY >
<!ATTLIST PROCESSED COUNT CDATA #REQUIRED >

<!ELEMENT SKIPPED ( OBJECT* ) >
<!ATTLIST SKIPPED COUNT CDATA #REQUIRED >

<!ELEMENT OBJECT EMPTY >
<!ATTLIST OBJECT NAME CDATA #REQUIRED >
<!ATTLIST OBJECT ERROR CDATA #REQUIRED >

<!ELEMENT CREATED EMPTY >
<!ATTLIST CREATED DATE CDATA #REQUIRED >
<!ATTLIST CREATED TIME CDATA #REQUIRED >

<!ELEMENT TRIGGER ( COMMENT | COMMENT_FIRST_LINE | DECLARATION | TAG )* >
<!ATTLIST TRIGGER NAME CDATA #REQUIRED >

<!ELEMENT DECLARATION EMPTY >
<!ATTLIST DECLARATION TEXT CDATA #REQUIRED >

=== radtek/plsql_os_command/apidoc/application.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE APPLICATION SYSTEM "application.dtd">
<APPLICATION NAME="File and operating system interaction with SQL and PLSQL">
<PACKAGE NAME="FILE_TYPE" SCHEMA="">
<COMMENT><![CDATA[ <b>FILE_TYPE</b> is an object type and
 represents a file handle. A file handle points to an existent or
 non-existent file in the database server's filesystem. All file
 operations are done as the operating user under which the Oracle
 executable runs. FILE_TYPE has the following attributes:<br>
 <br>
 <table style="border: 1px solid black;">
   <tbody>
     <tr>
       <td><b><tt>file_path</tt></b></td>
       <td><tt>VARCHAR2(4000)</tt></td>
       <td>The full path to the file</td>
     </tr>
     <tr>
       <td><b><tt>file_name</tt></b></td>
       <td><tt>VARCHAR2(4000)</tt></td>
       <td>The simple name of the file</td>
     </tr>
     <tr>
       <td><b><tt>file_size</tt></b></td>
       <td><tt>NUMBER</tt></td>
       <td>The size of the file in bytes</td>
     </tr>
     <tr>
       <td><b><tt>is_dir</tt></b></td>
       <td><tt>CHAR(1)</tt></td>
       <td>'Y' when the file is a directory, 'N' otherwise</td>
     </tr>
     <tr>
       <td><b><tt>is_writeable</tt></b></td>
       <td><tt>CHAR(1)</tt></td>
       <td>'Y' when the file is writeable, 'N' otherwise</td>
     </tr>
     <tr>
       <td><b><tt>is_readable</tt></b></td>
       <td><tt>CHAR(1)</tt></td>
       <td>'Y' when the file is readable, 'N' otherwise</td>
     </tr>
     <tr>
       <td><b><tt>file_exists</tt></b></td>
       <td><tt>CHAR(1)</tt></td>
       <td>'Y' when the handle points a an existing file; 'N'
 otherwise</td>
     </tr>
   </tbody>
 </table>
 <br>
 A file handle can point to existing files as well as to nonexisting
 files. The last attribute <b>file_exists</b> denotes
 whether the file handle points to an existing file. If not all other
 attributes except the <b>file_path</b> and the <b>file_name</b>
 are NULL. <br>
 <br>
 Example I: Obtaining a file handle for the /tmp directory (see
 documentation for FILE_PKG) </p>
 <pre> SQL&gt; select file_pkg.get_file('/tmp') from dual;<br> <br>
  FILE_PKG.GET_FILE('/TMP')(FILE_PATH, FILE_NAME, FILE_SIZE, LAST_MODIFIED, IS_DIR
  --------------------------------------------------------------------------------
  FILE_TYPE('/tmp', 'tmp', 77824, '26.03.08', 'Y', 'Y', 'Y', 'Y')
  </pre>
 Example II: Obtaining a file handle for the (nonexisting) /tmp1
 directory (see documentation for FILE_PKG)
 <pre> SQL&gt; select file_pkg.get_file('/tmp1') from dual;<br> <br>
  FILE_PKG.GET_FILE('/TMP1')(FILE_PATH, FILE_NAME, FILE_SIZE, LAST_MODIFIED, IS_DI
  --------------------------------------------------------------------------------
  FILE_TYPE('/tmp1', NULL, NULL, NULL, NULL, NULL, NULL, 'N')
  </pre>
 <br>
 The database user needs appropriate java privileges in order to operate
 on operating system files. The DBA must provide proper privileges using
 the built-in package DBMS_JAVA. The following call for example grants
 the privileges to read the directory <b>/tmp</b> and its
 contents to the database user <b>SCOTT</b>:
 <pre>begin<br>   dbms_java.grant_permission(<br>     grantee =&gt;           'SCOTT',<br>     permission_type =&gt;   'SYS:java.io.FilePermission',<br>     permission_name =&gt;   '/tmp/*',<br>     permission_action =&gt; 'read'<br>   );<br>end;<br> </pre>
 To grant read and write access to the whole file system, issue ...
 <pre>begin<br>   dbms_java.grant_permission(<br>     grantee =&gt;           'SCOTT',<br>     permission_type =&gt;   'SYS:java.io.FilePermission',<br>     permission_name =&gt;   '/-',<br>     permission_action =&gt; 'read,write'<br>   );<br>end;<br> </pre>
]]></COMMENT>
<VARIABLE NAME="file_path">
<COMMENT_FIRST_LINE><![CDATA[Full absolute path to this file
]]></COMMENT_FIRST_LINE>
<COMMENT><![CDATA[Full absolute path to this file
]]></COMMENT>
<RETURN TYPE="varchar2(4000)"/>
</VARIABLE>
<VARIABLE NAME="file_name">
<COMMENT_FIRST_LINE><![CDATA[Filename
]]></COMMENT_FIRST_LINE>
<COMMENT><![CDATA[Filename
]]></COMMENT>
<RETURN TYPE="varchar2(4000)"/>
</VARIABLE>
<VARIABLE NAME="file_size">
<COMMENT_FIRST_LINE><![CDATA[File size in bytes
]]></COMMENT_FIRST_LINE>
<COMMENT><![CDATA[File size in bytes
]]></COMMENT>
<RETURN TYPE="number"/>
</VARIABLE>
<VARIABLE NAME="last_modified">
<COMMENT_FIRST_LINE><![CDATA[LastModified date of this file
]]></COMMENT_FIRST_LINE>
<COMMENT><![CDATA[LastModified date of this file
]]></COMMENT>
<RETURN TYPE="date"/>
</VARIABLE>
<VARIABLE NAME="is_dir">
<COMMENT_FIRST_LINE><![CDATA[Flag whether this file is a directory ("Y"); "N" otherwise
]]></COMMENT_FIRST_LINE>
<COMMENT><![CDATA[Flag whether this file is a directory ("Y"); "N" otherwise
]]></COMMENT>
<RETURN TYPE="char(1)"/>
</VARIABLE>
<VARIABLE NAME="is_writeable">
<COMMENT_FIRST_LINE><![CDATA[Flag whether this file is writeable
]]></COMMENT_FIRST_LINE>
<COMMENT><![CDATA[Flag whether this file is writeable
]]></COMMENT>
<RETURN TYPE="char(1)"/>
</VARIABLE>
<VARIABLE NAME="is_readable">
<COMMENT_FIRST_LINE><![CDATA[Flag whether this file is readable
]]></COMMENT_FIRST_LINE>
<COMMENT><![CDATA[Flag whether this file is readable
]]></COMMENT>
<RETURN TYPE="char(1)"/>
</VARIABLE>
<VARIABLE NAME="file_exists">
<COMMENT_FIRST_LINE><![CDATA[Flag whether this file exists - if a file does not exist, all attributes except
this and the full pathname are set to SQL NULL.]]></COMMENT_FIRST_LINE>
<COMMENT><![CDATA[Flag whether this file exists - if a file does not exist, all attributes except
this and the full pathname are set to SQL NULL.
]]></COMMENT>
<RETURN TYPE="char(1)"/>
</VARIABLE>
<FUNCTION NAME="move">
<COMMENT_FIRST_LINE><![CDATA[performs a "move" / "rename" operation
]]></COMMENT_FIRST_LINE>
<COMMENT><![CDATA[performs a "move" / "rename" operation
]]></COMMENT>
<ARGUMENT DEFAULT="" MODE="" NAME="p_target_file" TYPE="file_type">
<COMMENT><![CDATA[FILE_TYPE object denoting the new file name and path.]]></COMMENT>
</ARGUMENT>
<RETURN TYPE="file_type">
<COMMENT><![CDATA[FILE_TYPE object pointing to the target file.]]></COMMENT>
</RETURN>
<TAG TYPE="@param">
<COMMENT><![CDATA[p_target_file FILE_TYPE object denoting the new file name and path.]]></COMMENT>
</TAG>
<TAG TYPE="@return">
<COMMENT><![CDATA[FILE_TYPE object pointing to the target file.]]></COMMENT>
</TAG>
</FUNCTION>
<FUNCTION NAME="delete_file">
<COMMENT_FIRST_LINE><![CDATA[deletes the file or directory.]]></COMMENT_FIRST_LINE>
<COMMENT><![CDATA[deletes the file or directory. If a directory contains other files an error message is thrown.
<pre>
SQL&gt; select file_pkg.get_file('/home/oracle/old_file.txt') file_exists from dual;

FILE_EXISTS
-----------------------------------------------------------------------------------------
FILE_TYPE('/home/oracle/old_file.txt', 'old_file.txt', 0, '03.02.10', 'N', 'Y', 'Y', 'Y')

SQL&gt; select file_pkg.get_file('/home/oracle/old_file.txt').delete_file() file_not_exists from duaL;

FILE_NOT_EXISTS
--------------------------------------------------------------------------------
FILE_TYPE('/home/oracle/old_file.txt', NULL, NULL, NULL, NULL, NULL, NULL, 'N')
</pre>
]]></COMMENT>
<RETURN TYPE="file_type">
<COMMENT><![CDATA[FILE_TYPE object pointing to the location of the deleted file with the FILE_EXISTS attribute being set to "N"]]></COMMENT>
</RETURN>
<TAG TYPE="@return">
<COMMENT><![CDATA[FILE_TYPE object pointing to the location of the deleted file with the FILE_EXISTS attribute being set to "N"]]></COMMENT>
</TAG>
</FUNCTION>
<FUNCTION NAME="delete_recursive">
<COMMENT_FIRST_LINE><![CDATA[deletes the file or directory.]]></COMMENT_FIRST_LINE>
<COMMENT><![CDATA[deletes the file or directory. Directory contents are being deleted recursively.
]]></COMMENT>
<RETURN TYPE="file_type">
<COMMENT><![CDATA[FILE_TYPE object pointing to the location of the deleted directory with the FILE_EXISTS attribute being set to "N"]]></COMMENT>
</RETURN>
<TAG TYPE="@return">
<COMMENT><![CDATA[FILE_TYPE object pointing to the location of the deleted directory with the FILE_EXISTS attribute being set to "N"]]></COMMENT>
</TAG>
</FUNCTION>
<FUNCTION NAME="make_file">
<COMMENT_FIRST_LINE><![CDATA[Creates a new empty file.]]></COMMENT_FIRST_LINE>
<COMMENT><![CDATA[Creates a new empty file. Must be called on a FILE_TYPE object with the FILE_EXISTS attribute set to "N"
<pre>
SQL&gt; select file_pkg.get_file('/home/oracle/new_file.txt') file_not_exists from duaL;

FILE_NOT_EXISTS
--------------------------------------------------------------------------------
FILE_TYPE('/home/oracle/new_file.txt', NULL, NULL, NULL, NULL, NULL, NULL, <b>'N'</b>)

SQL&gt; select file_pkg.get_file('/home/oracle/new_file.txt').make_file() file_exists from dual;

FILE_EXISTS
-----------------------------------------------------------------------------------------
FILE_TYPE('/home/oracle/new_file.txt', 'new_file.txt', 0, '03.02.10', 'N', 'Y', 'Y', 'Y')
</pre>
]]></COMMENT>
<RETURN TYPE="FILE_TYPE">
<COMMENT><![CDATA[FILE_TYPE object pointing to the new file]]></COMMENT>
</RETURN>
<TAG TYPE="@return">
<COMMENT><![CDATA[FILE_TYPE object pointing to the new file]]></COMMENT>
</TAG>
</FUNCTION>
<FUNCTION NAME="make_dir">
<COMMENT_FIRST_LINE><![CDATA[Creates a new empty directory.]]></COMMENT_FIRST_LINE>
<COMMENT><![CDATA[Creates a new empty directory. Work similar to the MAKE_FILE function.
]]></COMMENT>
<RETURN TYPE="FILE_TYPE">
<COMMENT><![CDATA[FILE_TYPE object pointing the new directory]]></COMMENT>
</RETURN>
<TAG TYPE="@return">
<COMMENT><![CDATA[FILE_TYPE object pointing the new directory]]></COMMENT>
</TAG>
</FUNCTION>
<FUNCTION NAME="create_dir">
<COMMENT_FIRST_LINE><![CDATA[Creates a new empty directory.]]></COMMENT_FIRST_LINE>
<COMMENT><![CDATA[Creates a new empty directory.
]]></COMMENT>
<ARGUMENT DEFAULT="" MODE="" NAME="p_dirname" TYPE="varchar2">
<COMMENT><![CDATA[absolute path to the new directory]]></COMMENT>
</ARGUMENT>
<RETURN TYPE="FILE_TYPE">
